#!/bin/bash

root=$(dirname "$(realpath $0)")
current=$root/current
shared=$root/shared

# Shared folders for Rails
for folder in public/uploads public/assets; do
  mkdir -p $shared/$folder
  [ -e $current/$folder ] || ln -sf $shared/$folder $current/$folder
done

# Shared folder for Caddy
mkdir -p ~/.local/share $shared/caddy
[ -e ~/.local/share/caddy ] || ln -sf $shared/caddy ~/.local/share/caddy

# Set defaults for discourse
set -a
: ${DISCOURSE_DB_POOL:=8}
: ${DISCOURSE_DB_TIMEOUT:=5000}
: ${DISCOURSE_DB_CONNECT_TIMEOUT:=5}
: ${DISCOURSE_DB_HOST:=postgres}
: ${DISCOURSE_DB_NAME:=$POSTGRES_USER}
: ${DISCOURSE_DB_USERNAME:=$POSTGRES_USER}
: ${DISCOURSE_DB_PASSWORD:=$POSTGRES_PASSWORD}
: ${DISCOURSE_REDIS_HOST:=redis}
: ${DISCOURSE_REDIS_PORT:=6379}
: ${DISCOURSE_REDIS_DB:=0}
set +a
