#!/bin/bash

set -e
source ./_configure

cat > /etc/caddy/Caddyfile << EOF

$HTTP_SCHEME://$DISCOURSE_HOSTNAME:3000/ {
  root * /app/current/public
  encode gzip
  log

  @notStatic {
    not {
      path /assets/*
    }
    not {
      path /stylesheets/*
    }
    not {
      path /uploads/*
    }
    not {
      file {
        try_files {path}
      }
    }
  }
  reverse_proxy @notStatic http://puma:3000
  file_server
}
EOF

exec /usr/bin/caddy run -config /etc/caddy/Caddyfile
