#!/bin/bash

set -e
source ./_configure

cat > /etc/caddy/Caddyfile << EOF

${CADDY_HOST:-$DISCOURSE_HOSTNAME}

root * /app/current/public
encode gzip

header /assets/* Cache-Control "max-age=31536000"

@notStatic {
  not {
    path /assets/*
  }
  not {
    path /uploads/*
  }
  not {
    path /images/*
  }
  not {
    file {
      try_files {path}
    }
  }
}
reverse_proxy @notStatic http://puma:3000

file_server
EOF

# Allow overriding the Caddyfile
caddyfile=$root/shared/caddy/Caddyfile
[ -e "$caddyfile" ] || caddyfile=/etc/caddy/Caddyfile

exec /usr/bin/caddy run -config "$caddyfile"
