#!/bin/bash

set -e

export RAILS_ENV=production
export NODE_ENV=production

cd current

bundle config set deployment 'true'
bundle config set without 'test development'
bundle install --jobs `nproc`

yarn install
