#!/bin/bash

set -e
source ./_configure

cd $root/current
rake db:migrate

precompiled=$root/shared/.assets-precompiled
if [ ! -e $precompiled ]; then
  rake assets:precompile
  touch $precompiled
fi

cat > config/puma.rb << EOF
# First, you need to change these below to your situation.
APP_ROOT = '${root}/current'

# Second, you can choose how many threads that you are going to run at same time.
workers 2
threads 8, 32
preload_app!

pidfile false
EOF

rm -f /app/current/tmp/pids/server.pid

exec bin/rails server --log-to-stdout
