#!/bin/bash

set -e
source ./_configure

cd $root/current
bundle exec rake db:migrate

reference=$root/current
precompiled=$root/shared/.assets-precompiled
if [ ! -e "$precompiled" ] || [ "$reference" -nt "$precompiled" ] || [ "$reference" -ot "$precompiled" ]; then
  bundle exec rake assets:precompile
  touch $precompiled -r $reference
fi

cat > config/puma.rb << EOF
# First, you need to change these below to your situation.
APP_ROOT = '${root}/current'

# Second, you can choose how many threads that you are going to run at same time.
workers 2
threads 8, 32
preload_app!

pidfile false
EOF

rm -f /app/current/tmp/pids/server.pid

exec bin/rails server --log-to-stdout
